const state={screen:'home',match:null,teamA:'Team A',teamB:'Team B',devices:[],selectedDeviceId:'',resolution:'720p',stream:null,cameraError:null,isRecording:false,elapsedMs:0,chunkCount:0,replayUrl:null,isReplayLoading:false,playbackRate:1,isPlaying:false,selectedReviewType:'LBW',pendingReviewId:null,showDecision:false,drawTool:'pitch',marks:{pitch:null,impact:null,stumps:null,lines:[]},assistResult:null};
const BUFFER_MS=120000,CHUNK_MS=3500;
let mediaRecorder=null,recordingActive=false,startTime=0,elapsedTimer=null,chunks=[],db=null,drawing=false,lineStart=null;
const RES={'480p':{w:854,h:480},'720p':{w:1280,h:720},'1080p':{w:1920,h:1080}};
async function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('cricket-drs-v3',1);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('chunks'))d.createObjectStore('chunks',{keyPath:'id'}).createIndex('byStart','startTime');};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function uid(){return crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+Math.random().toString(36).slice(2);}
function formatElapsed(ms){const s=Math.floor(ms/1000),m=Math.floor(s/60),sec=s%60;return String(m).padStart(2,'0')+':'+String(sec).padStart(2,'0');}
function formatOverBall(o,b){return o+'.'+b;}
function saveMatch(){try{localStorage.setItem('cricket-drs-match',JSON.stringify(state.match));}catch(e){}}
function loadMatch(){try{const r=localStorage.getItem('cricket-drs-match');return r?JSON.parse(r):null;}catch(e){return null;}}
async function listCameras(){try{const t=await navigator.mediaDevices.getUserMedia({video:true});t.getTracks().forEach(tr=>tr.stop());const all=await navigator.mediaDevices.enumerateDevices();state.devices=all.filter(d=>d.kind==='videoinput');if(state.devices.length&&!state.selectedDeviceId)state.selectedDeviceId=state.devices[0].deviceId;state.cameraError=null;}catch(e){state.cameraError=e.message||'Camera permission denied';}render();}
async function startCamera(){state.cameraError=null;try{if(state.stream)state.stream.getTracks().forEach(t=>t.stop());const r=RES[state.resolution];const s=await navigator.mediaDevices.getUserMedia({video:{deviceId:state.selectedDeviceId?{exact:state.selectedDeviceId}:undefined,width:{ideal:r.w},height:{ideal:r.h},facingMode:{ideal:'environment'}},audio:false});state.stream=s;const v=document.getElementById('liveVideo');if(v){v.srcObject=s;await v.play().catch(()=>{});}}catch(e){state.cameraError=e.message||'Failed to open camera';state.stream=null;}render();}
function pickMime(){for(const m of['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'])if(MediaRecorder.isTypeSupported(m))return m;return'';}
function startChunk(){if(!recordingActive||!state.stream)return;const mime=pickMime();if(!mime){state.cameraError='MediaRecorder not supported';render();return;}try{const rec=new MediaRecorder(state.stream,{mimeType:mime,videoBitsPerSecond:2500000});const id=uid(),parts=[],chunkStart=Date.now();rec.ondataavailable=e=>{if(e.data&&e.data.size>0)parts.push(e.data);};rec.onstop=()=>{if(!parts.length){if(recordingActive)startChunk();return;}const blob=new Blob(parts,{type:mime}),end=Date.now();chunks.push({id,blob,startTime:chunkStart,endTime:end,duration:end-chunkStart,preserved:false});const cutoff=end-BUFFER_MS-5000;chunks=chunks.filter(c=>c.endTime>cutoff||c.preserved);state.chunkCount=chunks.length;if(recordingActive)startChunk();renderStatus();};mediaRecorder=rec;rec.start();setTimeout(()=>{if(rec.state==='recording')rec.stop();},CHUNK_MS);}catch(e){state.cameraError=e.message||'Recorder error';render();}}
function startRecording(){if(!state.stream){startCamera().then(()=>{if(state.stream)startRecording();});return;}if(recordingActive)return;recordingActive=true;state.isRecording=true;startTime=Date.now();state.elapsedMs=0;elapsedTimer=setInterval(()=>{state.elapsedMs=Date.now()-startTime;renderStatus();},400);startChunk();render();}
async function getReplay(durationSec,aroundTs){const now=Date.now();let start,end=now;if(aroundTs){start=aroundTs-10000;end=Math.min(now,aroundTs+25000);}else start=now-durationSec*1000;let selected=chunks.filter(c=>c.endTime>=start&&c.startTime<=end);if(!selected.length){const latestEnd=chunks.length?Math.max(...chunks.map(c=>c.endTime)):now;start=latestEnd-durationSec*1000;selected=chunks.filter(c=>c.endTime>=start);}if(!selected.length)return null;selected.sort((a,b)=>a.startTime-b.startTime);selected.forEach(c=>c.preserved=true);return new Blob(selected.map(c=>c.blob),{type:selected[0].blob.type||'video/webm'});}
function createMatch(){state.match={id:uid(),teamA:state.teamA||'Team A',teamB:state.teamB||'Team B',teamAScore:0,teamAWickets:0,teamBScore:0,teamBWickets:0,currentOver:0,currentBall:0,status:'live',startTime:Date.now(),events:[],reviews:[]};saveMatch();state.screen='live';render();listCameras();}
function addEvent(type){if(!state.match)return;state.match.events.push({id:uid(),timestamp:Date.now(),type,ballNumber:state.match.currentBall,overNumber:state.match.currentOver});if(type==='BALL_DELIVERED'){let b=state.match.currentBall+1,o=state.match.currentOver;if(b>6){b=1;o+=1;}state.match.currentBall=b;state.match.currentOver=o;}saveMatch();render();}
function latestBallTs(){if(!state.match)return null;for(let i=state.match.events.length-1;i>=0;i--)if(state.match.events[i].type==='BALL_DELIVERED')return state.match.events[i].timestamp;return null;}
async function takeReview(duration){if(!state.isRecording){alert('Start continuous recording first');return;}state.isReplayLoading=true;state.marks={pitch:null,impact:null,stumps:null,lines:[]};state.assistResult=null;render();try{const around=duration==='last_ball'?latestBallTs():null;const sec=typeof duration==='number'?duration:60;const blob=await getReplay(sec,around);if(!blob){alert('Not enough footage yet.');state.isReplayLoading=false;render();return;}if(state.replayUrl)URL.revokeObjectURL(state.replayUrl);state.replayUrl=URL.createObjectURL(blob);state.playbackRate=1;state.isPlaying=false;state.showDecision=false;state.pendingReviewId=uid();state.match.reviews.push({id:state.pendingReviewId,timestamp:Date.now(),reviewType:state.selectedReviewType,over:state.match.currentOver,ball:state.match.currentBall});state.match.events.push({id:uid(),timestamp:Date.now(),type:'REVIEW_TAKEN',ballNumber:state.match.currentBall,overNumber:state.match.currentOver});saveMatch();state.screen='review';}catch(e){console.error(e);alert('Failed to create replay');}state.isReplayLoading=false;render();}
function setDecision(d){if(!state.match||!state.pendingReviewId)return;const r=state.match.reviews.find(x=>x.id===state.pendingReviewId);if(r){r.decision=d;r.assist=state.assistResult;}saveMatch();setTimeout(()=>{state.screen='live';if(state.replayUrl){URL.revokeObjectURL(state.replayUrl);state.replayUrl=null;}state.showDecision=false;render();},600);render();}
